import type { Metadata } from "next";
import { ReactNode } from "react";
import { Providers } from './providers';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Providers>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
